In [2]:
import numpy
import pandas as pd
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split


# 이건 import 잘 되나 예시 긁어온거,,,나중에 이해할 수 있겠지
data = {
    '학번' : range(2000, 2010)
    , '성적' : [85, 95, 75, 70, 100, 100, 95, 85, 80, 85]
}
print('일반')
print(pd.DataFrame(data))
print('----------------------------')
print('프레임 컬럼 순서 변경')
print(pd.DataFrame(data, columns = ['성적', '학번']))
print('----------------------------')
print('프레임 인덱스 나열 변경')
print(pd.DataFrame(data, columns = ['성적', '학번'], index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']))
print('행렬 변환')
print(pd.DataFrame(data, columns = ['성적', '학번'], index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']).transpose()) # or .T

일반
     학번   성적
0  2000   85
1  2001   95
2  2002   75
3  2003   70
4  2004  100
5  2005  100
6  2006   95
7  2007   85
8  2008   80
9  2009   85
----------------------------
프레임 컬럼 순서 변경
    성적    학번
0   85  2000
1   95  2001
2   75  2002
3   70  2003
4  100  2004
5  100  2005
6   95  2006
7   85  2007
8   80  2008
9   85  2009
----------------------------
프레임 인덱스 나열 변경
    성적    학번
a   85  2000
b   95  2001
c   75  2002
d   70  2003
e  100  2004
f  100  2005
g   95  2006
h   85  2007
i   80  2008
j   85  2009
행렬 변환
       a     b     c     d     e     f     g     h     i     j
성적    85    95    75    70   100   100    95    85    80    85
학번  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009


In [6]:
import numpy as np

# np.array() -> 리스트 형태의 데이터를 입력 받아 ndarray로 변환
# ndarray.shape -> ndarray의 차원과 크기를 튜플 형태로 나타내 준다.
array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)
# 1차원 array, 3개의 데이터

array2=np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)
# 2차원 array, 2개의 로우와 3개의 컬럼

array3=np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)
# 2차원 array, 1개의 로우와 3개의 컬럼

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [8]:
# ndarra.ndim -> 각 array의 차원
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


In [10]:
list1=[1,2,3]
print(type(list))
array1=np.array(list1)
print(type(array1))
# ndarray.dtype -> ndarray 내 데이터 타입 확인
print(array1, array1.dtype)

<class 'type'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [11]:
#데이터 유형이 셖여있는 리스트는 ndarray 변환시 데이터 크기가 더 큰 타입으로 형 변환 일괄 적용
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2, 3.0]
array3=np.array(list3)
print(array3, array3.dtype)


['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [13]:
array_int=np.array([1,2,3])
# ndarray.astype() -> ndarray 내 데이터 값의 타입 변경
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1,2.1,3.6])
# float -> int로 데이터 타입 변환 시 소수점은 버리기
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [15]:
# arange() -> range()와 같이 순차적으로 데이터 값 초기화
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [18]:
# zeors(), ones() -> 튜플 형태의 shape를 인자료 입력하면 모든 값을 0/1로 채운 ndarray 반환
zero_array=np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# 데이터 타입의 default는 float64
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [8]:
array1=np.arange(10)
print('array1:\n', array1)

# reshape() -> ndarray를 특정 차원 및 크기로 변환
# 변경이 불가능 하면 오류 발생
array2=array1.reshape(2,5)
print('array2:\n', array2)

array3=array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [13]:
array1=np.arange(10)
print(array1)
# -1을 인자로 사용하면 원래 ndarray랑 호환되는 새로운 shape로 변환
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [14]:
# 변환 불가능 하면 오류
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [16]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 cdarray로 변환
array5=array3d.reshape(-1,1)]
# tolist()를 이용해 리스트 자료형으로 변환 가능(시각적 이해를 위함)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [17]:
# 1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1, stop=10)
print('array1:', array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [18]:
# 마이너스 기호는 맨 뒤에서 부투, 인덱스 -1==맨 뒤의 데이터 값
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [19]:
# 단일 인덱스로 ndarray 내의 데이터값도 수정 가능
array1[0]=9
array1[8]=0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [21]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

# 콤마(,)로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근
print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [22]:
array1 = np.arange(start=1, stop=10)
# ':'기호를 이용하여 연속한 데이터를 슬라이싱해서 추출
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [23]:
array1=np.arange(start=1, stop=10)
# 시작 인덱스 생략시 default=0
array4=array1[:3]
print(array4)

# 종료 인덱스 생략시 default=-1(마지막 인덱스)
array5=array1[3:]
print(array5)

# 시작/종료 인덱스 생략시 맨 처음/맨 마지막 인덱스로 간주
array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [26]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n', array2d)

# 콤마(,)로 로우와 칼럼 인덱스 지칭
print('array2d[0:2, 0:2] \n', array2d[0:2,0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3,0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:,:])
print('array2d[:2, 1:] \n', array2d[:2,1:])
print('array2d[:2, 0] \n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [27]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [28]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)

# 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식
array3=array2d[[0,1],2]
print('array2d[[0,1],2] => ', array3.tolist())

#a array2d[[0,1], 0:2] == ((0,0), (0,1)), ((1,0), (1,1)) 인덱싱
array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ', array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


In [31]:
array1d=np.arange(start=1, stop=10)
# []안에 array1d > 5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:', array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [32]:
# 넘파이 ndarray 객체에 조건식을 할당한 결과
array1d>5
# False, True로 이뤄진 ndarray 객체 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [33]:
# 위 결과를 array1d 내에 인덱스로 입력하면 동일한 결과가 나옴
boolean_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [34]:
# 위와 같은 뜻
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


In [36]:
org_array=np.array([3,1,9,5])
print('원본 행렬:', org_array)
# np.sort()로 정렬 -> 원본 유지
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
# ndarrya.sort()로 정렬 -> 반환 None, 원본 변환
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [37]:
# 내림차순으로 정렬 -> [::-1]
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [38]:
array2d=np.array([[8,12],
                  [7,1]])

# 다차원 행렬은 axis 축 값 설정으로 통해 정렬 수행
sort_array2d_axis0=np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d, axis=1)
print('로우 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
로우 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [39]:
org_array=np.array([3,1,9,5])
# np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [40]:
org_array=np.array([3,1,9,5])
# 내림차순 정렬은 [::-1]
sort_indices_desc=np.argsort(org_array)[::-1]
print(type(sort_indices_desc))
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [42]:
import numpy as np
# 넘파이의 ndarray는 메타데이터를 가질 수 없으므로 실제 값과 그 값이 뜻하는 데타 데이터를 별도의 ndarray로 가져야 한다.

name_array=np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array=np.array([78, 95, 84, 98, 88])

# np.srgsort(score_array)를 이용해 반환된 인덱스를 name_array에 팬시 인덱스로 적용해 추출
sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indieces_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [43]:
A=np.array([[1,2,3],
           [4,5,6]])
B=np.array([[7,8],
           [9,10],
           [11,12]])

# np.dot() -> 행렬 내적(행렬 곱) 구하기
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [45]:
A=np.array([[1,2],
           [3,4]])
# np.transpose() -> 전치 행렬 구하기
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
